// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApUhHLMDNegk3GqFDCOdnNLMfKSVfM9IE',
    appId: '1:613617712461:web:3372db80fece7a99e00b04',
    messagingSenderId: '613617712461',
    projectId: 'koumeet-91744',
    authDomain: 'koumeet-91744.firebaseapp.com',
    storageBucket: 'koumeet-91744.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDszAGEyrJw6zLioU0zaFaSVW3iqDMVG1g',
    appId: '1:613617712461:android:6cb1d528a5ae07fbe00b04',
    messagingSenderId: '613617712461',
    projectId: 'koumeet-91744',
    storageBucket: 'koumeet-91744.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoTzak-XWkJqaZT-HoO27vy4A_Yj0bNcY',
    appId: '1:613617712461:ios:00b93afafe7caa38e00b04',
    messagingSenderId: '613617712461',
    projectId: 'koumeet-91744',
    storageBucket: 'koumeet-91744.appspot.com',
    iosClientId: '613617712461-be96b31ccumrr40qh314te7ge3pgagjg.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
